# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='views',
            new_name='long',
        ),
        migrations.AddField(
            model_name='page',
            name='lat',
            field=models.IntegerField(default=28),
        ),
    ]
