# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20171011_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='long',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
