# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20171011_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
